/*
Business Question:
How many customers belong to each value segment, and how much total
revenue does each segment generate?

Objective:
This query segments customers according to their lifetime revenue.

How The Query Works:
1. The subquery joins the Orders and Products tables so revenue can be
   calculated using units purchased multiplied by unit price.
2. SUM() calculates the lifetime revenue generated by each customer.
3. A CASE expression assigns every customer to one revenue segment:
   - VIP: $250 or more
   - Loyal: $150 to $249.99
   - Regular: $75 to $149.99
   - Occasional: $25 to $74.99
   - New: Less than $25
4. The outer query groups customers by their assigned segment.
5. COUNT(*) calculates the number of customers in each segment.
6. SUM(lifetime_revenue) calculates the total revenue generated by
   each segment.
7. The results are ordered from the highest-revenue segment to the lowest.
*/

SELECT
    customer_segment,
    COUNT(*) AS customer_count,
    ROUND(SUM(lifetime_revenue), 2) AS total_revenue
FROM
(
    SELECT
        o.customer_id,
        SUM(o.units * p.unit_price) AS lifetime_revenue,
       CASE
    WHEN SUM(o.units * p.unit_price) >= 250 THEN 'VIP'
    WHEN SUM(o.units * p.unit_price) >= 150 THEN 'Loyal'
    WHEN SUM(o.units * p.unit_price) >= 75 THEN 'Regular'
    WHEN SUM(o.units * p.unit_price) >= 25 THEN 'Occasional'
    ELSE 'New'
END AS customer_segment
    FROM orders o
    INNER JOIN products p
        ON o.product_id = p.product_id
    GROUP BY o.customer_id
) AS customer_segments
GROUP BY customer_segment
ORDER BY total_revenue DESC;