/*
Business Question:
Who are the company's highest-revenue customers, and what percentage of
total company revenue does each of them contribute?

Objective:
This query calculates the total revenue generated by each customer,
determines each customer's contribution to overall company revenue,
and returns the top 10 customers ranked by total revenue. 

How The Query Works:
1. A Common Table Expression (CTE) calculates the total revenue for each
   customer by multiplying the number of units purchased by the product's
   unit price and summing the revenue across all of their orders.
2. The main query retrieves each customer's total revenue.
3. A window function (SUM() OVER()) calculates the total revenue generated
   by all customers without collapsing the result set.
4. Each customer's revenue is divided by the overall company revenue and
   multiplied by 100 to calculate their percentage contribution.
5. The ROUND() function formats the revenue contribution percentage to
   two decimal places.
6. The results are sorted in descending order by customer revenue.
7. LIMIT 10 returns only the top 10 highest-revenue customers.

*/

WITH CustomerRevenue AS (
    SELECT
        o.customer_id,
        SUM(o.units * p.unit_price) AS customer_revenue
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
    GROUP BY
        o.customer_id
)

SELECT
    customer_id,
    customer_revenue,

    ROUND(
        customer_revenue /
        SUM(customer_revenue) OVER () * 100,
        2
    ) AS revenue_contribution_pct

FROM CustomerRevenue
ORDER BY
    customer_revenue DESC
   LIMIT 10